name: Build and Push Docker Image

on:
  push:
    # branches: [main, master]
    branches: ["*"]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      #================= SETUP =============
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #================= LOGIN =============
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #================= VERSION =============
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/front-end
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      #================= BUILD & PUSH =============
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./front-end/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/front-end:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/front-end:buildcache,mode=max
